#!/bin/sh

#echo "Executing instruction Level 2 ";
echo "Instruction for Level 4: \n";
echo ">>>Travel through the path created to Pandora. Wait for next instruction.\n";
sleep 10;
echo ">>>Hope you have reached Pandora safely. There is lot of cobwebs in the cave. Remove all the cobwebs.\n";
