#!/bin/sh


cob1="/tmp/pandora/.cobweb1";
cob2="/tmp/pandora/.cobweb2";
cob3="/tmp/pandora/.cobweb3";
cob4="/tmp/pandora/.cobweb4";
cob5="/tmp/pandora/.cobweb5";
cob6="/tmp/pandora/.cobweb6";


if [ -f "$cob1" ]; then
	exit 1
fi
if [ -f "$cob2" ]; then
	exit 1
fi
if [ -f "$cob3" ]; then
	exit 1
fi
if [ -f "$cob4" ]; then
	exit 1
fi
if [ -f "$cob5" ]; then
	exit 1
fi
if [ -f "$cob6" ]; then
	exit 1
fi
exit 0
